version: '3.0'

expectations:
  population_size: 100000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/input.csv.gz

  generate_study_population_ba2:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_ba2 --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/input_ba2.csv.gz

  data_process:
    run: r:latest analysis/data_process.R
    needs: [generate_study_population]
    outputs:
      highly_sensitive:
        data1: output/data/data_processed_day0.rds
        data2: output/data/data_processed_day5.rds

  data_process_ba2:
    run: r:latest analysis/data_process_ba2.R
    needs: [generate_study_population_ba2]
    outputs:
      highly_sensitive:
        data1: output/data/ba2_data_processed_day0.rds
        data2: output/data/ba2_data_processed_day5.rds      

  data_properties_process_day0:
    run: r:latest analysis/data_properties.R output/data/data_processed_day0.rds output/data_properties
    needs: [data_process]
    outputs:
      moderately_sensitive:
        txt1: output/data_properties/data_processed_day0_skim.txt
        txt2: output/data_properties/data_processed_day0_coltypes.txt
        txt3: output/data_properties/data_processed_day0_tabulate.txt

  data_properties_process_day5:
    run: r:latest analysis/data_properties.R output/data/data_processed_day5.rds output/data_properties
    needs: [data_process]
    outputs:
      moderately_sensitive:
        txt1: output/data_properties/data_processed_day5_skim.txt
        txt2: output/data_properties/data_processed_day5_coltypes.txt
        txt3: output/data_properties/data_processed_day5_tabulate.txt

  data_properties_process_day0_ba2:
    run: r:latest analysis/data_properties.R output/data/ba2_data_processed_day0.rds output/data_properties
    needs: [data_process_ba2]
    outputs:
      moderately_sensitive:
        txt1: output/data_properties/ba2_data_processed_day0_skim.txt
        txt2: output/data_properties/ba2_data_processed_day0_coltypes.txt
        txt3: output/data_properties/ba2_data_processed_day0_tabulate.txt

  data_properties_process_day5_ba2:
    run: r:latest analysis/data_properties.R output/data/ba2_data_processed_day5.rds output/data_properties
    needs: [data_process_ba2]
    outputs:
      moderately_sensitive:
        txt1: output/data_properties/ba2_data_processed_day5_skim.txt
        txt2: output/data_properties/ba2_data_processed_day5_coltypes.txt
        txt3: output/data_properties/ba2_data_processed_day5_tabulate.txt

  crosstab_trt_outcomes:
    run: r:latest analysis/crosstab_trt_outcomes.R
    needs: [data_process]
    outputs:
      moderately_sensitive:
        csvsday5: output/data_properties/day5_*.csv 
        csvsday0: output/data_properties/day0_*.csv
        csvflowchart: output/data_properties/flowchart.csv
        csvflowchartrdctd: output/tables/flowchart_redacted.csv

  crosstab_trt_outcomes_ba2:
    run: r:latest analysis/crosstab_trt_outcomes_ba2.R
    needs: [data_process_ba2]
    outputs:
      moderately_sensitive:
        csvsday5: output/data_properties/ba2_day5_*.csv 
        csvsday0: output/data_properties/ba2_day0_*.csv
        csvflowchart: output/data_properties/flowchart_ba2.csv
        csvflowchartrdctd: output/tables/flowchart_redacted_ba2.csv

  table_1_day5:
    run: r:latest analysis/table_1.R day5
    needs: [data_process]
    outputs:
      highly_sensitive:
        data: output/tables/table1_redacted_day5_new.rds
      moderately_sensitive:
        table: output/tables/table1_redacted_day5_new.html

  table_1_day5_ba2:
    run: r:latest analysis/table_1_ba2.R day5
    needs: [data_process_ba2]
    outputs:
      highly_sensitive:
        data: output/tables/table1_redacted_day5_ba2_new.rds
      moderately_sensitive:
        table: output/tables/table1_redacted_day5_ba2_new.html

  cox_day5_full:
    run: r:latest analysis/cox_models.R day5 full
    needs: [data_process]
    outputs:
      highly_sensitive:
        data: output/tables/cox_models_day5_full_new.rds
      moderately_sensitive:
        figure1: output/figs/*_full_overlap_plot_day5_before_restriction_new.png
        figure2: output/figs/*_full_overlap_plot_day5_after_restriction_new.png
        figure3: output/figs/*_full_cumInc_day5_new.png
        table1: output/tables/cox_models_day5_full_new.csv
        table2: output/tables/log_cox_models_day5_full_new.csv
        model1: output/data_models/*_full_psModelFit_new.rds

  cox_day5_full_ba2:
    run: r:latest analysis/cox_models_ba2.R day5 full
    needs: [data_process_ba2]
    outputs:
      moderately_sensitive:
        figure1: output/figs/*_full_overlap_plot_day5_before_restriction_ba2_new.png
        figure2: output/figs/*_full_overlap_plot_day5_after_restriction_ba2_new.png
        figure3: output/figs/*_full_cumInc_day5_ba2_new.png
        table1: output/tables/cox_models_day5_full_ba2_new.csv
        table2: output/tables/log_cox_models_day5_full_ba2_new.csv
        model1: output/data_models/*_full_psModelFit_ba2_new.rds

  cox_day5_age_sex:
    run: r:latest analysis/cox_models.R day5 agesex
    needs: [data_process]
    outputs:
      highly_sensitive:
        data: output/tables/cox_models_day5_agesex_new.rds
      moderately_sensitive:
        figure1: output/figs/*_agesex_overlap_plot_day5_before_restriction_new.png
        figure2: output/figs/*_agesex_overlap_plot_day5_after_restriction_new.png
        figure3: output/figs/*_agesex_cumInc_day5_new.png
        table1: output/tables/cox_models_day5_agesex_new.csv
        table2: output/tables/log_cox_models_day5_agesex_new.csv
        model1: output/data_models/*_agesex_psModelFit_new.rds

  cox_day5_age_sex_ba2:
    run: r:latest analysis/cox_models_ba2.R day5 agesex
    needs: [data_process_ba2]
    outputs:
      highly_sensitive:
        data: output/tables/cox_models_day5_agesex_ba2_new.rds
      moderately_sensitive:
        figure1: output/figs/*_agesex_overlap_plot_day5_before_restriction_ba2_new.png
        figure2: output/figs/*_agesex_overlap_plot_day5_after_restriction_ba2_new.png
        figure3: output/figs/*_agesex_cumInc_day5_ba2_new.png
        table1: output/tables/cox_models_day5_agesex_ba2_new.csv
        table2: output/tables/log_cox_models_day5_agesex_ba2_new.csv
        model1: output/data_models/*_agesex_psModelFit_ba2_new.rds
  
  cox_day5_crude:
    run: r:latest analysis/cox_models.R day5 crude
    needs: [data_process]
    outputs:
      highly_sensitive:
        data: output/tables/cox_models_day5_crude_new.rds
      moderately_sensitive:
        table1: output/tables/cox_models_day5_crude_new.csv
        table2: output/tables/log_cox_models_day5_crude_new.csv

  cox_day5_crude_ba2:
    run: r:latest analysis/cox_models_ba2.R day5 crude
    needs: [data_process_ba2]
    outputs:
      highly_sensitive:
        data: output/tables/cox_models_day5_crude_ba2_new.rds
      moderately_sensitive:
        table1: output/tables/cox_models_day5_crude_ba2_new.csv
        table2: output/tables/log_cox_models_day5_crude_ba2_new.csv
        
  trt_pat_day5:
    run: r:latest analysis/treatment_distributions.R day5
    needs: [data_process]
    outputs:
      moderately_sensitive:
        figure: output/figs/day5_treatment_pattern.png

  cox_day0:
    run: r:latest analysis/cox_models_day0.R
    needs: [data_process]
    outputs:
      highly_sensitive:
        data: output/tables/cox_models_day0.rds
      moderately_sensitive:
        table1: output/tables/cox_models_day0.csv
        table2: output/tables/estimates_day0.csv
        table3: output/tables/log_cox_models_day0.csv
        table4: output/tables/outcomes_day0.csv
  
  ## # # # # # # # # # # # # # # # # # # # 
  ## Subgroup
  ## # # # # # # # # # # # # # # # # # # #    

  cox_day5_full_organ:
    run: r:latest analysis/cox_models_organ.R day5 full
    needs: [data_process]
    outputs:
      highly_sensitive:
        data: output/tables/cox_models_day5_full_organ_new.rds
      moderately_sensitive:
        figure1: output/figs/*_full_overlap_plot_day5_before_restriction_organ_new.png
        figure2: output/figs/*_full_overlap_plot_day5_after_restriction_organ_new.png
        figure3: output/figs/*_full_cumInc_day5_organ_new.png
        table1: output/tables/cox_models_day5_full_organ_new.csv
        table2: output/tables/log_cox_models_day5_full_organ_new.csv
        model1: output/data_models/*_full_psModelFit_organ_new.rds

  cox_day5_age_sex_organ:
    run: r:latest analysis/cox_models_organ.R day5 agesex
    needs: [data_process]
    outputs:
      highly_sensitive:
        data: output/tables/cox_models_day5_agesex_organ_new.rds
      moderately_sensitive:
        figure1: output/figs/*_agesex_overlap_plot_day5_before_restriction_organ_new.png
        figure2: output/figs/*_agesex_overlap_plot_day5_after_restriction_organ_new.png
        figure3: output/figs/*_agesex_cumInc_day5_organ_new.png
        table1: output/tables/cox_models_day5_agesex_organ_new.csv
        table2: output/tables/log_cox_models_day5_agesex_organ_new.csv
        model1: output/data_models/*_agesex_psModelFit_organ_new.rds
  
  cox_day5_crude_organ:
    run: r:latest analysis/cox_models_organ.R day5 crude
    needs: [data_process]
    outputs:
      highly_sensitive:
        data: output/tables/cox_models_day5_crude_organ_new.rds
      moderately_sensitive:
        table1: output/tables/cox_models_day5_crude_organ_new.csv
        table2: output/tables/log_cox_models_day5_crude_organ_new.csv

  cox_day5_full_organ_ba2:
    run: r:latest analysis/cox_models_organ_ba2.R day5 full
    needs: [data_process_ba2]
    outputs:
      highly_sensitive:
        data: output/tables/cox_models_day5_full_ba2_organ_new.rds
      moderately_sensitive:
        figure1: output/figs/*_full_overlap_plot_day5_before_restriction_ba2_organ_new.png
        figure2: output/figs/*_full_overlap_plot_day5_after_restriction_ba2_organ_new.png
        figure3: output/figs/*_full_cumInc_day5_ba2_organ_new.png
        table1: output/tables/cox_models_day5_full_ba2_organ_new.csv
        table2: output/tables/log_cox_models_day5_full_ba2_organ_new.csv
        model1: output/data_models/*_full_psModelFit_ba2_organ_new.rds

  cox_day5_age_sex_organ_ba2:
    run: r:latest analysis/cox_models_organ_ba2.R day5 agesex
    needs: [data_process_ba2]
    outputs:
      highly_sensitive:
        data: output/tables/cox_models_day5_agesex_ba2_organ_new.rds
      moderately_sensitive:
        figure1: output/figs/*_agesex_overlap_plot_day5_before_restriction_ba2_organ_new.png
        figure2: output/figs/*_agesex_overlap_plot_day5_after_restriction_ba2_organ_new.png
        figure3: output/figs/*_agesex_cumInc_day5_ba2_organ_new.png
        table1: output/tables/cox_models_day5_agesex_ba2_organ_new.csv
        table2: output/tables/log_cox_models_day5_agesex_ba2_organ_new.csv
        model1: output/data_models/*_agesex_psModelFit_ba2_organ_new.rds
  
  cox_day5_crude_organ_ba2:
    run: r:latest analysis/cox_models_organ_ba2.R day5 crude
    needs: [data_process_ba2]
    outputs:
      highly_sensitive:
        data: output/tables/cox_models_day5_crude_ba2_organ_new.rds
      moderately_sensitive:
        table1: output/tables/cox_models_day5_crude_ba2_organ_new.csv
        table2: output/tables/log_cox_models_day5_crude_ba2_organ_new.csv

  cox_day5_full_haem_malig:
    run: r:latest analysis/cox_models_haem_malig.R day5 full
    needs: [data_process]
    outputs:
      highly_sensitive:
        data: output/tables/cox_models_day5_full_haem_malig_new.rds 
      moderately_sensitive:
        figure1: output/figs/*_full_overlap_plot_day5_before_restriction_haem_malig_new.png
        figure2: output/figs/*_full_overlap_plot_day5_after_restriction_haem_malig_new.png
        figure3: output/figs/*_full_cumInc_day5_haem_malig_new.png
        table1: output/tables/cox_models_day5_full_haem_malig_new.csv
        table2: output/tables/log_cox_models_day5_full_haem_malig_new.csv
        model1: output/data_models/*_full_psModelFit_haem_malig_new.rds

  cox_day5_age_sex_haem_malig:
    run: r:latest analysis/cox_models_haem_malig.R day5 agesex
    needs: [data_process]
    outputs:
      highly_sensitive:
        data: output/tables/cox_models_day5_agesex_haem_malig_new.rds
      moderately_sensitive:
        figure1: output/figs/*_agesex_overlap_plot_day5_before_restriction_haem_malig_new.png
        figure2: output/figs/*_agesex_overlap_plot_day5_after_restriction_haem_malig_new.png
        figure3: output/figs/*_agesex_cumInc_day5_haem_malig_new.png
        table1: output/tables/cox_models_day5_agesex_haem_malig_new.csv
        table2: output/tables/log_cox_models_day5_agesex_haem_malig_new.csv
        model1: output/data_models/*_agesex_psModelFit_haem_malig_new.rds

  cox_day5_crude_haem_malig:
    run: r:latest analysis/cox_models_haem_malig.R day5 crude
    needs: [data_process]
    outputs:
      highly_sensitive:
        data: output/tables/cox_models_day5_crude_haem_malig_new.rds
      moderately_sensitive:
        table1: output/tables/cox_models_day5_crude_haem_malig_new.csv
        table2: output/tables/log_cox_models_day5_crude_haem_malig_new.csv

  cox_day5_full_haem_malig_ba2:
    run: r:latest analysis/cox_models_haem_malig_ba2.R day5 full
    needs: [data_process_ba2]
    outputs:
      highly_sensitive:
        data: output/tables/cox_models_day5_full_ba2_haem_malig_new.rds 
      moderately_sensitive:
        figure1: output/figs/*_full_overlap_plot_day5_before_restriction_ba2_haem_malig_new.png
        figure2: output/figs/*_full_overlap_plot_day5_after_restriction_ba2_haem_malig_new.png
        figure3: output/figs/*_full_cumInc_day5_ba2_haem_malig_new.png
        table1: output/tables/cox_models_day5_full_ba2_haem_malig_new.csv
        table2: output/tables/log_cox_models_day5_full_ba2_haem_malig_new.csv
        model1: output/data_models/*_full_psModelFit_ba2_haem_malig_new.rds

  cox_day5_age_sex_haem_malig_ba2:
    run: r:latest analysis/cox_models_haem_malig_ba2.R day5 agesex
    needs: [data_process_ba2]
    outputs:
      highly_sensitive:
        data: output/tables/cox_models_day5_agesex_ba2_haem_malig_new.rds
      moderately_sensitive:
        figure1: output/figs/*_agesex_overlap_plot_day5_before_restriction_ba2_haem_malig_new.png
        figure2: output/figs/*_agesex_overlap_plot_day5_after_restriction_ba2_haem_malig_new.png
        figure3: output/figs/*_agesex_cumInc_day5_ba2_haem_malig_new.png
        table1: output/tables/cox_models_day5_agesex_ba2_haem_malig_new.csv
        table2: output/tables/log_cox_models_day5_agesex_ba2_haem_malig_new.csv
        model1: output/data_models/*_agesex_psModelFit_ba2_haem_malig_new.rds

  cox_day5_crude_haem_malig_ba2:
    run: r:latest analysis/cox_models_haem_malig_ba2.R day5 crude
    needs: [data_process_ba2]
    outputs:
      highly_sensitive:
        data: output/tables/cox_models_day5_crude_ba2_haem_malig_new.rds
      moderately_sensitive:
        table1: output/tables/cox_models_day5_crude_ba2_haem_malig_new.csv
        table2: output/tables/log_cox_models_day5_crude_ba2_haem_malig_new.csv

        