version: '3.0'

expectations:
  population_size: 100000

actions:

  ## # # # # # # # # # # # # # # # # # # # 
  ## Data extraction 
  ## # # # # # # # # # # # # # # # # # # # 

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/input.csv.gz

  generate_study_population_ba2:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_ba2 --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/input_ba2.csv.gz

  ## # # # # # # # # # # # # # # # # # # # 
  ## Data cleaning and description
  ## # # # # # # # # # # # # # # # # # # # 

  data_process:
    run: r:latest analysis/data_process.R ba1
    needs: [generate_study_population]
    outputs:
      highly_sensitive:
        data: output/data/data_processed.rds

  data_process_ba2:
    run: r:latest analysis/data_process.R ba2
    needs: [generate_study_population_ba2]
    outputs:
      highly_sensitive:
        data1: output/data/ba2_data_processed.rds   

  data_properties:
    run: r:latest analysis/data_properties/data_properties.R output/data/data_processed.rds output/data_properties
    needs: [data_process]
    outputs:
      moderately_sensitive:
        txt1: output/data_properties/data_processed_skim.txt
        txt2: output/data_properties/data_processed_coltypes.txt
        txt3: output/data_properties/data_processed_tabulate.txt

  data_properties_ba2:
    run: r:latest analysis/data_properties/data_properties.R output/data/ba2_data_processed.rds output/data_properties
    needs: [data_process_ba2]
    outputs:
      moderately_sensitive:
        txt1: output/data_properties/ba2_data_processed_skim.txt
        txt2: output/data_properties/ba2_data_processed_coltypes.txt
        txt3: output/data_properties/ba2_data_processed_tabulate.txt
  
  sense_check:
    run: r:latest analysis/data_properties/sense_check.R ba1
    needs: [data_process]
    outputs:
      moderately_sensitive:
        csv: output/data_properties/sense_checks.txt

  sense_check_ba2:
    run: r:latest analysis/data_properties/sense_check.R ba2
    needs: [data_process_ba2]
    outputs:
      moderately_sensitive:
        csv: output/data_properties/ba2_sense_checks.txt

  ## # # # # # # # # # # # # # # # # # # # 
  ## CCW Analysis - Day 0 
  ## # # # # # # # # # # # # # # # # # # # 

  ## # # # # # # # # # # # # # # # # # # # 
  ## Tables
  ## # # # # # # # # # # # # # # # # # # # 