version: '3.0'

expectations:
  population_size: 100000

actions:

  ## # # # # # # # # # # # # # # # # # # # 
  ## Data extraction 
  ## # # # # # # # # # # # # # # # # # # # 

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/input.csv.gz

  generate_study_population_ba2:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_ba2 --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/input_ba2.csv.gz

  ## # # # # # # # # # # # # # # # # # # # 
  ## Data cleaning and description
  ## # # # # # # # # # # # # # # # # # # # 

  data_process:
    run: r:latest analysis/data_process.R ba1
    needs: [generate_study_population]
    outputs:
      highly_sensitive:
        data: output/data/data_processed_day*.rds

  data_process_ba2:
    run: r:latest analysis/data_process.R ba2
    needs: [generate_study_population_ba2]
    outputs:
      highly_sensitive:
        data1: output/data/ba2_data_processed_day*.rds   

  data_properties_process_day0:
    run: r:latest analysis/data_properties.R output/data/data_processed_day0.rds output/data_properties
    needs: [data_process]
    outputs:
      moderately_sensitive:
        txt1: output/data_properties/data_processed_day0_skim.txt
        txt2: output/data_properties/data_processed_day0_coltypes.txt
        txt3: output/data_properties/data_processed_day0_tabulate.txt

  data_properties_process_day0_ba2:
    run: r:latest analysis/data_properties.R output/data/ba2_data_processed_day0.rds output/data_properties
    needs: [data_process_ba2]
    outputs:
      moderately_sensitive:
        txt1: output/data_properties/ba2_data_processed_day0_skim.txt
        txt2: output/data_properties/ba2_data_processed_day0_coltypes.txt
        txt3: output/data_properties/ba2_data_processed_day0_tabulate.txt
  
  crosstab_trt_outcomes:
    run: r:latest analysis/crosstab_trt_outcomes.R ba1
    needs: [data_process]
    outputs:
      moderately_sensitive:
        csvsdays: output/data_properties/day*.csv

  crosstab_trt_outcomes_ba2:
    run: r:latest analysis/crosstab_trt_outcomes.R ba2
    needs: [data_process_ba2]
    outputs:
      moderately_sensitive:
        csvsdays: output/data_properties/ba2_day*.csv

  ## # # # # # # # # # # # # # # # # # # # 
  ## CCW Analysis - Day 0 
  ## # # # # # # # # # # # # # # # # # # # 

  ## # # # # # # # # # # # # # # # # # # # 
  ## Tables
  ## # # # # # # # # # # # # # # # # # # # 