covars_smd <- 
  c("age",
    "sex_female",
    "ethnicity_Unknown",
    "ethnicity_White",
    "ethnicity_Mixed",
    "ethnicity_Asian",
    "ethnicity_Black",
    "ethnicity_Other",
    "imd_1",
    "imd_2",
    "imd_3",
    "imd_4",
    "imd_5",
    "rural_urban_conurbation",
    "rural_urban_citytown",
    "rural_urban_townfringe",
    "rural_urban_villagedisp",
    # other comorbidities/clinical characteristics
    "obese",
    "smoking_Smoker",
    "smoking_Ever",
    "smoking_Never",
    "smoking_Unknown",
    "diabetes",
    "chronic_cardiac_disease",
    "copd",
    "dialysis",
    "serious_mental_illness_nhsd",
    "learning_disability_primis",
    "dementia_nhsd",
    "autism_nhsd",
    "care_home_primis",
    "housebound_opensafely",
    # high risk group
    "downs_syndrome_nhsd",
    "cancer_opensafely_snomed_new", # non-overlapping
    "haematological_disease_nhsd",
    "ckd_stage_5_nhsd", 
    "liver_disease_nhsd", 
    "imid_nhsd",
    "immunosupression_nhsd_new", # non-overlapping
    "hiv_aids_nhsd",
    "solid_organ_transplant_nhsd_new", # non-overlapping
    "multiple_sclerosis_nhsd", 
    "motor_neurone_disease_nhsd",
    "myasthenia_gravis_nhsd",
    "huntingtons_disease_nhsd",
    # vax vars
    "vax_status_3",
    "vax_status_2",
    "vax_status_1",
    "vax_status_unvax",
    "vax_status_declined",
    "tb_postest_vax_Unknown",
    "tb_postest_vax_7",
    "tb_postest_vax_7_27",
    "tb_postest_vax_28_83",
    "tb_postest_vax_84",
    "pfizer_most_recent_cov_vac",
    "az_most_recent_cov_vac",
    "moderna_most_recent_cov_vac",
    "no_most_recent_cov_vac")