#######
## Function to clean table names
clean_smd_names = function(input_table) {
  input_table %>%
    mutate(
      covars = case_when(covars == "age" ~ "Age",
                         covars == "sex_female" ~ "Sex",
                         covars == "ethnicity_Unknown" ~ "Ethnicity: Unknown",
                         covars == "ethnicity_White" ~ "Ethnicity: White",
                         covars == "ethnicity_Asian" ~ "Ethnicity: Asian",
                         covars == "ethnicity_Black" ~ "Ethnicity: Black",
                         covars == "ethnicity_Other" ~ "Ethnicity: Other",
                         covars == "ethnicity_Mixed" ~ "Ethnicity: Mixed",
                         covars == "imd_5" ~ "IMD: 5",
                         covars == "imd_4" ~ "IMD: 4",
                         covars == "imd_3" ~ "IMD: 3",
                         covars == "imd_2" ~ "IMD: 2",
                         covars ==  "imd_1" ~ "IMD: 1",
                         covars == "smoking_Smoker" ~ "Smoking: Current",
                         covars == "smoking_Unknown" ~ "Smoking: Unknown",
                         covars == "smoking_Never" ~ "Smoking: Never",
                         covars == "smoking_Ever" ~ "Smoking: Ever",
                         covars == "diabetes" ~ "Diabetes",
                         covars == "copd" ~ "COPD",
                         covars == "dialysis" ~ "Dialysis",
                         covars == "cancer" ~ "Cancer",
                         covars == "lung_cancer" ~ "Lung cancer",
                         covars == "haem_cancer" ~ "Haematological cancer",
                         covars == "az_most_recent_cov_vac" ~ "Most recent C-19 Vac: AZ",
                         covars == "moderna_most_recent_cov_vac" ~ "Most recent C-19 Vac: Moderna",
                         covars == "pfizer_most_recent_cov_vac" ~ "Most recent C-19 Vac: Pfizer",
                         covars == "no_most_recent_cov_vac" ~ "Most recent C-19 Vac: Unvaccinated",
                         covars == "vax_status_unvax" ~ "Vaccination status: Unvaccinated",
                         covars == "vax_status_declined" ~ "Vaccination status: Declined",
                         covars == "vax_status_3" ~ "Vaccination status: 3",
                         covars == "vax_status_2" ~ "Vaccination status: 2",
                         covars == "vax_status_1" ~ "Vaccination status: 1",
                         covars == "variant" ~ "Variant",
                         covars == "sgtf" ~ "SGTF",
                         covars == "rural_urban_villagedisp" ~ "Rural Urban: Village/Disp",
                         covars == "rural_urban_townfringe" ~ "Rural Urban: Town Fringe",
                         covars == "rural_urban_conurbation" ~ "Rural Urban: Conurbation",
                         covars == "rural_urban_citytown" ~ "Rural Urban: City/Town",
                         covars == "huntingtons_disease_nhsd" ~ "Huntington’s disease",
                         covars == "myasthenia_gravis_nhsd" ~ "Myasthenia gravis",
                         covars == "motor_neurone_disease_nhsd" ~ "Motor neurone disease",
                         covars == "multiple_sclerosis_nhsd" ~ "Multiple sclerosis",
                         covars == "solid_organ_transplant_new" ~ "Solid organ transplant",
                         covars == "hiv_aids_nhsd" ~ "HIV/AIDs",
                         covars == "immunosupression_new" ~ "Immune deficiencies",
                         covars == "imid_nhsd" ~ "Immune-mediated inflammatory disorders (IMID)",
                         covars == "liver_disease_nhsd" ~ "Liver disease",
                         covars == "ckd_stage_5_nhsd" ~ "Renal disease",
                         covars == "haematological_disease_nhsd" ~ "Haematological diseases",
                         covars == "non_haem_cancer_new" ~ "Solid cancer",
                         covars == "downs_syndrome_nhsd" ~ "Down's syndrome",
                         covars == "autism_nhsd" ~ "Autism",
                         covars == "care_home_primis" ~ "Care home",
                         covars == "dementia_nhsd" ~ "Dementia",
                         covars == "housebound_opensafely" ~ "Housebound",
                         covars == "serious_mental_illness_nhsd" ~ "Severe mental illness",
                         covars == "chronic_cardiac_disease" ~ "Chronic cardiac disease",
                         covars == "cancer_opensafely_snomed_new" ~ "Cancer",
                         covars == "solid_organ_transplant_nhsd_new" ~ "Solid organ transplant",
                         covars == "learning_disability_primis" ~ "Learning disability",
                         covars == "immunosupression_nhsd_new" ~ "Immunosupression",
                         covars == "region_nhs_yorkshire_humber" ~ "Region: Yorkshire/The Humber",
                         covars ==  "region_nhs_west_midlands" ~ "Region: West Midlands",
                         covars == "region_nhs_south_east" ~ "Region: South East",
                         covars == "region_nhs_south_west" ~ "Region: South West",
                         covars == "region_nhs_north_west" ~ "Region: North West",
                         covars == "region_nhs_north_east" ~ "Region: North East",
                         covars == "region_nhs_london" ~ "Region: London",
                         covars == "region_nhs_east_midlands" ~ "Region: East Midlands",
                         covars == "region_nhs_east" ~ "Region: East",
                         covars == "obese" ~ "Obese",
                         TRUE ~ covars))
}
